version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # For data persistence
    command: redis-server --appendonly yes  # Enable AOF persistence
    restart: always

  faceit_stats_provider:
    image: "${DOCKERHUB_USERNAME}/faceitstatsprovider:${DOCKER_TAG}"
    ports:
      - "80:80"  # Only map HTTP port
    environment:
      - ASPNETCORE_URLS=http://+:80  
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT} 
    depends_on:
      - redis
    restart: always

volumes:
  redis-data:
    driver: local  # Ensures Redis data persists between restarts
