version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # For data persistence
    restart: always

  faceit_stats_provider:
    build:
      context: .
      dockerfile: Faceit_Stats_Provider/Dockerfile
    image: faceitstatsprovider
    ports:
      - "80:80"  # Only map HTTP port
    environment:
      - ASPNETCORE_URLS=http://+:80  # Ensure HTTPS is not included
      - ASPNETCORE_ENVIRONMENT=Production  # Set environment to Production
    depends_on:
      - redis
    restart: always

volumes:
  redis-data:
