version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data  # For data persistence
    command: redis-server --appendonly yes  # Enable AOF persistence
    restart: always

  faceit_stats_provider:
    image: "majder0/faceitstatsprovider:prod"
    build:
      context: .
      dockerfile: Faceit_Stats_Provider/Dockerfile
    ports:
      - "80:80"  
      - "443:443"    
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
    volumes:
      - ./Faceit_Stats_Provider/appsettings.json:/app/appsettings.json:ro  # Mount appsettings.json as read-only
    depends_on:
      - redis
    restart: always

volumes:
  redis-data:
    driver: local  # Ensures Redis data persists between restarts
